To find whether the vector is numeric/character/logical/complex data?

In [1]:
a <-c(1,2,3,4)

In [2]:
is.numeric(a)

[1] TRUE

If you have a data which has a mix of numeric data and character data then it recognizes as character. To cross chec, simply type b, and you will see that 1 and 2 also comes in inverted coma which is a feature of character

In [3]:
b<-c(1,2,"sk")

In [4]:
is.numeric(b)

[1] FALSE

In [5]:
is.character(b)

[1] TRUE

In [6]:
b

[1] "1"  "2"  "sk"

If you want to label numeric data as character data then 

In [7]:
as.character(a)

[1] "1" "2" "3" "4"

If you want to label logical data (True or False) as 1 and 2 respectively. In the example below, 1 value is denoted for true and 0 value is denoted for false 

In [8]:
d<-c(TRUE,TRUE,FALSE)
d

[1]  TRUE  TRUE FALSE

In [9]:
as.numeric (d)

[1] 1 1 0

In [10]:
d <- as.numeric(d)
d

[1] 1 1 0

In [11]:
d<-as.logical(d)
d

[1]  TRUE  TRUE FALSE

If the data has the labels like 33 and 55 which does not denote true or false then, R will automatically consider all positive nos as true.

In [12]:
e<-c(0,1,33,55)
e

[1]  0  1 33 55

In [13]:
e<-as.logical(e)
e

[1] FALSE  TRUE  TRUE  TRUE

VECTORS EXPLAINED

Assigning Values to the Vectors

In [14]:
num.a<-c(1,2,4,6,7)
num.a

[1] 1 2 4 6 7

Assigning automatic way to assign values from 1 to 10 (1)

In [15]:
num.b<-c(1:10)
num.b

[1]  1  2  3  4  5  6  7  8  9 10

Assigning automatic way to assign values from 1 to 10, including other values

In [16]:
num.b<-c(1:10,17,19)
num.b

[1]  1  2  3  4  5  6  7  8  9 10 17 19

Assigning automatic way to assign values from 1 to 10 (2)

In [17]:
num.d<-c(seq(1,10))
num.d

[1]  1  2  3  4  5  6  7  8  9 10

Assigning the values in sequence and selecting specific data, by writing 3 i.e., dividing the data into 3

In [18]:
num.e<-c(seq(1,10, by=3))
num.e

[1]  1  4  7 10

Assigning character values to the vector

In [19]:
char.a<-c('a','b','c','d','e')
char.a

[1] "a" "b" "c" "d" "e"

Checking whether the values entered above are character

In [20]:
class(char.a)

[1] "character"

Assigning 2 value to character b

In [21]:
char.a[2]

[1] "b"

Assigning 2 to 4 values to character b,c,d

In [22]:
char.a[2:4]

[1] "b" "c" "d"

Converting char.a to num.a (character to numeric values)

In [23]:
num.a

[1] 1 2 4 6 7

Assigning names to num.a like how we denote sequence

In [24]:
names(num.a)<-c("a","b","c","d","e")
names(num.a)

[1] "a" "b" "c" "d" "e"

Checking whether the character b value is 2

In [25]:
num.a[2]

b 
2

In [26]:
num.a["b"]

b 
2

FACTORS EXPLAINED

In [27]:
student.height<-c(130,121,122,111,109,111,141,131,114)

In [28]:
mean(student.height)

[1] 121.1111

In [29]:
summary(student.height)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  109.0   111.0   121.0   121.1   130.0   141.0 

In [30]:
airports<-c('DEL','CAL','NYC','CAL','DEL','DEL')

In [31]:
summary(airports)

   Length     Class      Mode 
        6 character character 

Level of data: Nominal, Ordinal, Interval, Ratio

Airport=Nominal data so convert into Factor

In [32]:
factor(airports)

[1] DEL CAL NYC CAL DEL DEL
Levels: CAL DEL NYC

In [33]:
airport.fact<-factor(airports)
airport.fact

[1] DEL CAL NYC CAL DEL DEL
Levels: CAL DEL NYC

In [34]:
summary(airport.fact)

CAL DEL NYC 
  2   3   1

In [35]:
birth.month=c("March","April","January","November","January","September","October","September","September","November","August","January","November","November","February","May","August","December","August","August","September","November","February","April")
birth.month

[1] "March"     "April"     "January"   "November"  "January"   "September"
 [7] "October"   "September" "September" "November"  "August"    "January"  
[13] "November"  "November"  "February"  "May"       "August"    "December" 
[19] "August"    "August"    "September" "November"  "February"  "April"

In [36]:
summary(birth.month)

   Length     Class      Mode 
       24 character character 

In [37]:
birth.month.fact<-factor(birth.month)
birth.month.fact

[1] March     April     January   November  January   September October  
 [8] September September November  August    January   November  November 
[15] February  May       August    December  August    August    September
[22] November  February  April    
10 Levels: April August December February January March May ... September

In [38]:
summary(birth.month.fact)

April    August  December  February   January     March       May  November 
        2         4         1         2         3         1         1         5 
  October September 
        1         4

In [39]:
months<-c("January","February","March","April","May","June","July","August","September","October","November","December")

Above is an ordinal data, so you can predefine the levels

In [40]:
birth.month.fact<-factor(birth.month,ordered=TRUE,levels=months)
birth.month.fact

[1] March     April     January   November  January   September October  
 [8] September September November  August    January   November  November 
[15] February  May       August    December  August    August    September
[22] November  February  April    
12 Levels: January < February < March < April < May < June < ... < December

In [41]:
summary(birth.month.fact)

January  February     March     April       May      June      July    August 
        3         2         1         2         1         0         0         4 
September   October  November  December 
        4         1         5         1

In [42]:
table(birth.month.fact)

birth.month.fact
  January  February     March     April       May      June      July    August 
        3         2         1         2         1         0         0         4 
September   October  November  December 
        4         1         5         1 

LIST EXPLAINED

List can club everything in bundle

In [43]:
a<-c(1,4,6)
a

[1] 1 4 6

In [44]:
b<-c('Red','Green')
b

[1] "Red"   "Green"

In [45]:
c<-"welcome"
c

[1] "welcome"

In [46]:
my.list<-list(a,b,c)
my.list

[[1]]
[1] 1 4 6

[[2]]
[1] "Red"   "Green"

[[3]]
[1] "welcome"

Way to label each list (of a,b,c)

In [47]:
my.list.n<-list(Pieces=a, Colors=b, Message=c)
my.list.n

$Pieces
[1] 1 4 6

$Colors
[1] "Red"   "Green"

$Message
[1] "welcome"

Different ways to remove to selected list

In [48]:
my.list.n[1]

$Pieces
[1] 1 4 6

In [49]:
my.list.n['Colors']

$Colors
[1] "Red"   "Green"

In [50]:
my.list.n$Message

[1] "welcome"

MATRIX EXPLAINED

Matrix:2 dimensional data but Vector: 1 dimensional data
Matrix helps to create tables of data

In [51]:
stu.hours<-c(20,24,46,62,22,37,45,27,65,23)
stu.hours

[1] 20 24 46 62 22 37 45 27 65 23

In [52]:
stu.marks<-c(40,55,69,83,27,44,61,33,71,37)
stu.marks

[1] 40 55 69 83 27 44 61 33 71 37

In [53]:
stu.matrix<-matrix(stu.hours)
stu.matrix

[,1]
 [1,] 20  
 [2,] 24  
 [3,] 46  
 [4,] 62  
 [5,] 22  
 [6,] 37  
 [7,] 45  
 [8,] 27  
 [9,] 65  
[10,] 23

Above shows data of hours in tabular form

In [54]:
stu.data<-c(stu.hours,stu.marks)
stu.data

[1] 20 24 46 62 22 37 45 27 65 23 40 55 69 83 27 44 61 33 71 37

Above shows data of hours and marks together

In [55]:
stu.matrix<-matrix(stu.data)
stu.matrix

[,1]
 [1,] 20  
 [2,] 24  
 [3,] 46  
 [4,] 62  
 [5,] 22  
 [6,] 37  
 [7,] 45  
 [8,] 27  
 [9,] 65  
[10,] 23  
[11,] 40  
[12,] 55  
[13,] 69  
[14,] 83  
[15,] 27  
[16,] 44  
[17,] 61  
[18,] 33  
[19,] 71  
[20,] 37

Single column which shows data of both hours and marks but we need 2 tables 

In [56]:
stu.matrix<-matrix(stu.data,nrow=10)
stu.matrix

[,1] [,2]
 [1,] 20   40  
 [2,] 24   55  
 [3,] 46   69  
 [4,] 62   83  
 [5,] 22   27  
 [6,] 37   44  
 [7,] 45   61  
 [8,] 27   33  
 [9,] 65   71  
[10,] 23   37

Selected 10 because there are 10 values for hours and 10 values for marks
The left column is hours and right column is marks

In [57]:
stu.matrix<-matrix(stu.data,byrow=T,nrow=10)
stu.matrix

[,1] [,2]
 [1,] 20   24  
 [2,] 46   62  
 [3,] 22   37  
 [4,] 45   27  
 [5,] 65   23  
 [6,] 40   55  
 [7,] 69   83  
 [8,] 27   44  
 [9,] 61   33  
[10,] 71   37

Above data shows hours and marks BUTTTTT the top 5 rows shows hours data and bottom 5 rows shows marks data
CHECK byrow=T (True); if you type false, the data will again show like the data in 56

In [58]:
stu.matrix<-matrix(stu.data,byrow=F,nrow=10)
stu.matrix

[,1] [,2]
 [1,] 20   40  
 [2,] 24   55  
 [3,] 46   69  
 [4,] 62   83  
 [5,] 22   27  
 [6,] 37   44  
 [7,] 45   61  
 [8,] 27   33  
 [9,] 65   71  
[10,] 23   37

Now how to label the columns?

In [59]:
colnames(stu.matrix)<-c('Hours','Marks')
rownames(stu.matrix)<-c(1:10)
stu.matrix

Hours Marks
1  20    40   
2  24    55   
3  46    69   
4  62    83   
5  22    27   
6  37    44   
7  45    61   
8  27    33   
9  65    71   
10 23    37

IFYOU DONT WANT TO USE MATRIX THEN YOU CAN IMPORT THE FILE AS EXCEL (csv file)

<code>read.csv('Student Marks.csv')</code>

IF YOU WANT TO IMPORT DATA FROM EXCEL (csv file), ABOVE IS THE COMMAND

BELOW, will allow to tell which value is present in a particular rowand column resp.

In [60]:
stu.matrix[4,2]

[1] 83


<code>stu.matrix[4,2]</code>

29. DATA FRAMES EXPLAINED

When you have mixture of data: Numeric, Character, Logical; then use Data frame and not Matrix

In [61]:
stu.name<-c('Mr1','Ms2','Ms3','Mr4','Ms5','Ms6','Mr7','Ms8','Mr9','Mr10')
stu.hours<-c(20,24,46,62,22,37,45,27,65,23)
stu.marks<-c(40,55,69,83,27,44,61,33,71,37)
stu.male<-c(T,F,F,T,F,F,T,F,T,T)
stu.name
stu.hours
stu.marks
stu.male

[1] "Mr1"  "Ms2"  "Ms3"  "Mr4"  "Ms5"  "Ms6"  "Mr7"  "Ms8"  "Mr9"  "Mr10"

[1] 20 24 46 62 22 37 45 27 65 23

[1] 40 55 69 83 27 44 61 33 71 37

[1]  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE

In [62]:
stu.data<-data.frame(stu.name,stu.hours,stu.marks,stu.male)
stu.data

stu.name stu.hours stu.marks stu.male
1  Mr1      20        40         TRUE   
2  Ms2      24        55        FALSE   
3  Ms3      46        69        FALSE   
4  Mr4      62        83         TRUE   
5  Ms5      22        27        FALSE   
6  Ms6      37        44        FALSE   
7  Mr7      45        61         TRUE   
8  Ms8      27        33        FALSE   
9  Mr9      65        71         TRUE   
10 Mr10     23        37         TRUE

In [63]:
summary(stu.data)

    stu.name   stu.hours       stu.marks      stu.male      
 Mr1    :1   Min.   :20.00   Min.   :27.00   Mode :logical  
 Mr10   :1   1st Qu.:23.25   1st Qu.:37.75   FALSE:5        
 Mr4    :1   Median :32.00   Median :49.50   TRUE :5        
 Mr7    :1   Mean   :37.10   Mean   :52.00                  
 Mr9    :1   3rd Qu.:45.75   3rd Qu.:67.00                  
 Ms2    :1   Max.   :65.00   Max.   :83.00                  
 (Other):4                                                  

In [64]:
mean(stu.data$stu.hours)

[1] 37.1

In [65]:
stu.data

stu.name stu.hours stu.marks stu.male
1  Mr1      20        40         TRUE   
2  Ms2      24        55        FALSE   
3  Ms3      46        69        FALSE   
4  Mr4      62        83         TRUE   
5  Ms5      22        27        FALSE   
6  Ms6      37        44        FALSE   
7  Mr7      45        61         TRUE   
8  Ms8      27        33        FALSE   
9  Mr9      65        71         TRUE   
10 Mr10     23        37         TRUE

In [66]:
stu.data[3,1]

[1] Ms3
Levels: Mr1 Mr10 Mr4 Mr7 Mr9 Ms2 Ms3 Ms5 Ms6 Ms8

In [67]:
stu.data[3,]

stu.name stu.hours stu.marks stu.male
3 Ms3      46        69        FALSE

In [68]:
stu.data[,2]

[1] 20 24 46 62 22 37 45 27 65 23

In [71]:
read.csv('Student Marks.csv')

ï..Hours.Studied Test.Score
1  20               40        
2  24               55        
3  46               69        
4  62               83        
5  22               27        
6  37               44        
7  45               61        
8  27               33        
9  65               71        
10 23               37

df<-read.csv('student marks.csv')

summary(df)